jamie-password: ENC[AES256_GCM,data:FD58op0zMKuyHGckJTQAUExWfPEbfuBvhJfQbrx39ItPLqBBQZwufgcqITTDidO6iWpXvndzIUgrxZrHK8eBlAK8CUR5RInkIg==,iv:1WCasa+A8ZmLnrT5u5y67f0J8uNPmMXIgWs/bk4Qqms=,tag:5qsn3LuyN5P/Z2MTbJAKNA==,type:str]
calendar-personal: ENC[AES256_GCM,data:7jMGUZkUSArZ2llDP1PIy380tCtV7U4GVTStvl3WVnhhm11AzzmKctBvodSLup1KbGI5Ncd/yK2r5tE6dvhclConuzzKnfMaFt4ZemD5j+b6tIaC/FiOC2vWuiG/FR+FRcYaiqnjBWdTstrd9Ma+PmkLav1BOoyQjEMKtuFwyhkUI/CwfSKoHIXmEcj0Khs3Ltn26fyt2OGhSZ+zZIRXlNSQrBlopLXmlshb+AqTs5OH8YaC1QoVK1gJWvEV3BJ5IjKYjts997W83Vekbb5KCiX8rCR+/qD7+IR1OSFyCkR7b+4VaQrgWr9mapKFiJbSup3tTPuPyw==,iv:i2rX8Hn0uCIA+ivah4CB2F8MUtBsCq4UBVCjOKJI87I=,tag:XLqIvpvyfNCZub1aJMjR4Q==,type:str]
calendar-work: ENC[AES256_GCM,data:zB/ZkeR84kJu/bMdvGNpLg94BJoEhF0gukpWXb1ft502A6RSsHtnWYewDyuwzJ8l187aCcqDVsSjdDDojLoWFeq2j/7GCoUo70ro79icZsz5otzb/oLw75kXIRCacc8v42JPqPHOrs6AOA8fkrrTTW5TtXRoG3KF+wHus/8FqZ1MHTqZmc2n8r91oC8CS7LKNH6DdrXv/b9XTkE52J6DsJB9s5BH36rQtqUpYjEdKhpbhAGZOx0yMjPIbC6pl7YUu6kJynesPPrmwTpg3vVHckyhiGPktpfImfqeU0ENDqmBJ9xTj5WY1XGPeeH6M+1hkRgNeEteRg==,iv:ZoBxCfgRNwPV/4JaJvkIxtfZe+VHCuraFHfQ0WY243I=,tag:+MEqBCx0wJMN4JyeWzf2cQ==,type:str]
wakapi-env: ENC[AES256_GCM,data:+6h8k1OaJgrRCkvSVlqdHuke8Czoj5dLZHeKNrKzrx2GKJft9wpefS6DCNr6EtsmeUOlXFpNRVx/NRrsH9FhdtWhvg==,iv:Q6twhRWBpzY33TN48UG9Gyzji7wP4ZSUOSHz2Mukfmk=,tag:ysZRO4UpWjtQ3/LMLqhcqA==,type:str]
wakapi-key: ENC[AES256_GCM,data:NfTPF+iFkksnsRhgWNU+dmAjseS1mfe6Yrm/FXmygLPcKCCI,iv:gDnpZFibixQtS65tQl80XmoCnkmvutOD/yC0p+Wg4E4=,tag:BaEKHUIF3VJnvGYoFcFvfA==,type:str]
sops:
    age:
        - recipient: age1689hns6xrgas8fc8dk809m48qeetlfvu9au3942ewhyqe7kyye3qdvzdtc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2Rza1luR0trTHp3L09y
            SEppTGRxdEFwak5vZ0I1eGhXeW1OMnlnY1ZrCjAzTU9UWVUvaS8yREF4V3pUSVEy
            WUJnK2hOb3FjRHB1SGdVSG12UGhiMzQKLS0tIEVjU0t3YlJFbnozYnBudkdybFNa
            ekRDQmpEd2tEV2FmZ0xoYVNkUU1SWW8KGTPWpiR39uDNBy/g0mA3vx0DTQgMSJug
            OzGHtTP0IuFW+SJTx/RHeQwnKOMH38jjZ34EgVDsirKBPVi4fpb1LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14zp3stx7nnwqkze488ckacz6h9u4ed3p8v92jyvv0lxhnw6qxp6qnn28a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNi96S1Z5WDZJdGZVTTNG
            SFY0cGMwR3hlR2FHdWlIMUZSUURVQ0o3dTJVClVIMWxKRmVpSGlpekZoOUtQdk1Z
            K0dsSHhkVVdpcHVKMzJqeEloT25qNVkKLS0tIGN1V0RLdW1Idy9tdVc2cGZ3Vll4
            U2M3Nm0xd1J3WkZMYVNGYXhHQlVZaGcKA0Y9MmzoDaBt6tofLZd4ZPc0NfGVaci6
            tao8Kv3zom0f8+1Dp7Zis9O98LMKEife6ZE9jFAvshSFXKdFROuWmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1salqmxagycvhs8unnddzwyg3aptn3tp9g7g7g5p25w3urw5kxvds72swg9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1c5b0FlWmt5UEJ3eHpH
            aDR0RE1zWGRyYVppRzc2enlMRklEdlJUcHlFCll4MTdIb1VmU3YraDJyTEJoQndm
            ckdLTUFUeTZ2cnRVdXovaXVGMVRLb1UKLS0tIG1SV0V3cVFqbGJUYWs2SkpIWWEw
            YUs0RjJSdFpzS3RJWUxGSmNzZzBWa3MK+MQT0rtCqa+h/U3ULRxDu5OWl6ez3aVM
            tLj0JWg01L2IUeu6lNHynAzAM487K7SlItz6Y5Cf3HDs1WBH1OuESw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18ewzvkpaj65c8c8jr5e90sw9dwrnu56vznf3exgydd65edpd4gnsqxsmx6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ0h5NWtxTjJuZ3pEUnFz
            b3cxYncwaUZwNEZJVlQ3ZXAzQU9pcG8wc25ZCndtSWNMUkUrNUVMUWpEYm42Y2pn
            YUlLQ2lDOUJtdHZoamgwaTV5TzlFM28KLS0tIDBYNXhqK1Z6U1liV0xnbG9nZlJS
            VENkRk80NkhxU3lLbWJCSy9TbWpGN2sKq2QCSecs9PNTtk0HWgN8pIzrue2T2RoJ
            6live5Kbb1NhDkTDxRtSSIJduMYwU0nn5gUYJz6BraR2WpguIth1ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T00:08:18Z"
    mac: ENC[AES256_GCM,data:XFDFUu15PvVVmVVkLKyJO+iiE57EXEWT3YuQI0/n3caszNROFFXDDxTohfetVm8Lh0cpgnW1+kjlRrjxnqVumOw7iPOfa9B3i0ft2Q4Kvx2xruBvFZX/1P4xG2aa5E45RMaGBUAZkdhPNEB7jB/u/7gHc5CmdfNxVEAen0xsXN0=,iv:esEOteleO3cdaaqY6obv8ETHzj8uBmywk8CDHpfYAfQ=,tag:rEQZkDNtQRfV8J61+IiRUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
