# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260722-484daf4e";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260722-484daf4e/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-43x69iZaxKCvbVe8ZehhCad22ZZug0MzRVf2PaSCUW8=";
    };
  };
  modern-minimal-ui-sounds = {
    pname = "modern-minimal-ui-sounds";
    version = "V1.2";
    src = fetchFromGitHub {
      owner = "cadecomposer";
      repo = "modern-minimal-ui-sounds";
      rev = "V1.2";
      fetchSubmodules = false;
      sha256 = "sha256-l8/nxuzBns2cyhGFral+XrTGSbI6jasoBvowQz72VOI=";
    };
  };
  photocraft = {
    pname = "photocraft";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "storytold";
      repo = "photocraft";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-4zwDB+4pccU3cB1YxTd6g1v13e5VCaaS3giZMsUKTJs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-4zwDB+4pccU3cB1YxTd6g1v13e5VCaaS3giZMsUKTJs=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  proton-cachyos_x86_64_v3 = {
    pname = "proton-cachyos_x86_64_v3";
    version = "cachyos-11.0-20260703-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260703-slr/proton-cachyos-11.0-20260703-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-A+zUK9fUdOm6RDzoly2WeKH6Osvykg12HzU5eUbs4oQ=";
    };
  };
}
