# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  ...
}:
{
  apple-emoji = {
    pname = "apple-emoji";
    version = "macos-26-20260219-2aa12422";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/macos-26-20260219-2aa12422/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "13b5b0c299982bb361039601e2d72587d6846294";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes.git";
      rev = "13b5b0c299982bb361039601e2d72587d6846294";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4eu3LqB9tPqe0Vaqxd4wkZiBbthLbpb7llcoE/p5HT0=";
    };
    date = "2026-03-04";
  };
  equibop-bin = {
    pname = "equibop-bin";
    version = "3.1.9";
    src = fetchurl {
      url = "https://github.com/Equicord/Equibop/releases/download/v3.1.9/Equibop-3.1.9-universal.dmg";
      sha256 = "sha256-S0DY0UzesPo+xggX1s3ERHByW2L+c/znlC+X1LIUV94=";
    };
  };
  helium-appimage = {
    pname = "helium-appimage";
    version = "0.10.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.7.1/helium-0.10.7.1-x86_64.AppImage";
      sha256 = "sha256-+vmxXcg8TkR/GAiHKnjq4b04bGtQzErfJkOb4P4nZUk=";
    };
  };
  helium-dmg = {
    pname = "helium-dmg";
    version = "0.10.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-macos/releases/download/0.10.7.1/helium_0.10.7.1_arm64-macos.dmg";
      sha256 = "sha256-zQUIP9LoZnjPKyvxPAOmyOsNp/cr0EBSxX0YEdmJO58=";
    };
  };
  hyprland-preview-share-picker = {
    pname = "hyprland-preview-share-picker";
    version = "344394a8669fb82ff2744d2780327dd402ffb76a";
    src = fetchFromGitHub {
      owner = "WhySoBad";
      repo = "hyprland-preview-share-picker";
      rev = "344394a8669fb82ff2744d2780327dd402ffb76a";
      fetchSubmodules = true;
      sha256 = "sha256-dreIL3+GfrTxzN5ZoQvLvEc8qFlTs/qwQZjPFJS1eJQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-dreIL3+GfrTxzN5ZoQvLvEc8qFlTs_qwQZjPFJS1eJQ=/Cargo.lock";
      outputHashes = {

      };
    };
    date = "2026-03-04";
  };
  liga-sf-mono-nerd-font = {
    pname = "liga-sf-mono-nerd-font";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  morewaita-icon-theme = {
    pname = "morewaita-icon-theme";
    version = "v49";
    src = fetchgit {
      url = "https://github.com/somepaulo/MoreWaita.git";
      rev = "v49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DxZ7XnIIF3EKGMPXahD+aHp6lCLRmrnywn7+qWCVflo=";
    };
  };
  owo-sh = {
    pname = "owo-sh";
    version = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
    src = fetchgit {
      url = "https://owo.codes/whats-this/owo.sh.git";
      rev = "d6ffda964cd6c81030f8e5516ca57c80a5a5dcb2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vwvUiM7mOixyNERjITwcS90jz15QFkwxCEtYzqm+hdg=";
    };
    date = "2023-04-10";
  };
  pearcleaner-bin = {
    pname = "pearcleaner-bin";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.dmg";
      sha256 = "sha256-+hTyxyRhCbM3OzRiqoFxel+iSIr6QcpcWoc4TIh0mqY=";
    };
  };
  proton-cachyos_x86_64_v3 = {
    pname = "proton-cachyos_x86_64_v3";
    version = "cachyos-10.0-20260321-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260321-slr/proton-cachyos-10.0-20260321-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-WBIaIj9P1yUYySFfbDOxZGx/CPxDCz6okoqRvYu5Epg=";
    };
  };
  proton-cachyos_x86_64_v4 = {
    pname = "proton-cachyos_x86_64_v4";
    version = "cachyos-10.0-20260321-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260321-slr/proton-cachyos-10.0-20260321-slr-x86_64_v4.tar.xz";
      sha256 = "sha256-eAOS+mWQa/4guK2H0yGBno3HFZ4g/gv/hxZiXq/VMHc=";
    };
  };
  protonpass-bin = {
    pname = "protonpass-bin";
    version = "1.35.0";
    src = fetchurl {
      url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_1.35.0.dmg";
      sha256 = "sha256-zwV1jBbtplM7TdS1KkEi813Z2ex45z3BP2ZA72s6pxE=";
    };
  };
  protonvpn-bin = {
    pname = "protonvpn-bin";
    version = "6.1.0";
    src = fetchurl {
      url = "https://vpn.protondownload.com/download/macos/6.1.0/ProtonVPN_mac_v6.1.0.dmg";
      sha256 = "sha256-u/J32eIgpQkvF87j4Lc3IKT0YkJHTx4JauL6TsXg/ls=";
    };
  };
  swipeaerospace-bin = {
    pname = "swipeaerospace-bin";
    version = "0.2.5";
    src = fetchurl {
      url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/0.2.5/SwipeAeroSpace.zip";
      sha256 = "sha256-v3zjXCxCS2Vsjqoc+vYvbN3hiBKy2Jh+uIrG2ZSPmn0=";
    };
  };
}
